<?php echo $this->render('admin/header.phtml');?>
<?php echo $this->render('admin/sidebar.phtml');?>

<div class="has-sidebar sm-padded" >
    <div class="has-sidebar-content" id="post-body-content">
        <h2 class="tabs" id="post-body-content-tabs">
            <a href="?page=sphinxsearch.php" class="nav-tab">Settings</a>
            <a href="?page=sphinxsearch.php&menu=stats" class="nav-tab nav-tab-active">Search terms</a>
        </h2>

        <ul class="subsubsub">
            <?php if($this->view->tab == 'new'):?>
                <li class='all'><a href='?page=sphinxsearch.php&menu=stats' class="current">New</a> |</li>
            <?php else:?>
                <li class='all'><a href='?page=sphinxsearch.php&menu=stats'>New</a> |</li>
            <?php endif; ?>
            <?php if($this->view->tab == 'ban'):?>
                <li class='moderated'><a href='?page=sphinxsearch.php&menu=stats&tab=ban' class="current">Banned</a> |</li>
            <?php else:?>
                <li class='moderated'><a href='?page=sphinxsearch.php&menu=stats&tab=ban'>Banned</a> |</li>
            <?php endif; ?>
            <?php if($this->view->tab == 'approved'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=approved' class="current">Approved</a> |</li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=approved'>Approved</a> |</li>
            <?php endif; ?>

            <?php if($this->view->tab == 'stats'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=stats' class="current">Statistics</a> </li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=stats'>Statistics</a> </li>
            <?php endif; ?>
        </ul>


    <?php
    if($this->view->tab == 'stats'){
        echo $this->render('admin/stats/stats.phtml');
    } else {
        echo $this->render('admin/stats/index.phtml');
    }
    ?>
    </div>
</div>

<?php echo $this->render('admin/footer.phtml');?>