

        <ul class="subsubsub">
            <?php if($this->view->tab == 'stats'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=stats' class="current">Statistics</a> </li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=stats&tab=stats'>Statistics</a> </li>
            <?php endif; ?>
        </ul>


    <?php
    if($this->view->tab == 'stats'){
        echo $this->render('admin/stats/stats.phtml');
    } else {
        echo $this->render('admin/stats/index.phtml');
    }
    ?>
    </div>
</div>
