
        <div class="meta-box-sortabless">
            <div id="wizard_page">
                <div class="postbox">
                    <h3 class="hndle">Sphinx Search Wizard</h3>
                    <div class="inside">
                    <form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" id="wizard_form">
                        <input type="hidden" name="start_process" value="1" />
                        <input type="hidden" name="action" value="start" />
                        <p>This is Sphinx Search configuration Wizard!</p>
                            <p class="submit">
                                <input class="button-primary" type="button"
                                       onClick="return wizard_next();" value="Start Wizard" />
                                <input class="button-secondary cancel alignright" type="button"                                       
                                       onClick="return wizard_cancel();" value="Cancel Wizard" />
                            </p>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

