<script type='text/javascript' src='<?php echo plugins_url('jquery-1.4.4.min.js', dirname(__FILE__)); ?>'></script>

<link rel='stylesheet' href='<?php echo plugins_url('styles/styles.css', __FILE__); ?>' type='text/css' media='all' />


<script type="text/javascript">
    function wizard_next() {
        var formData = $("#wizard_form").serialize();
        
        $('#wizard_page').html('<p style="text-align:center;width:100%;"><img src="<?php echo plugins_url('img/loadinfo.gif', __FILE__); ?>" /></p>');

        $.post("<?php echo site_url()?>/wp-admin/admin-ajax.php",
            formData,
            function(data)
            {
                if (data)
                  $('#wizard_page').html(data);

            }
        );
        return false;
    }
    function wizard_skip(page) {
         $("#wizard_form").append("<input type='hidden' name='skip_wizard_"+page+"' value='1' />");
         return wizard_next();
    }
    function wizard_cancel() {
         $("#wizard_form input[name=action]").val("stop");
         return wizard_next();
    }
</script>



<div class=wrap>
    <h2><?php echo $this->view->header?></h2>

    <?php echo $this->render('admin/messagebox.phtml'); ?>