<div class="has-sidebar sm-padded" >
    <div class="has-sidebar-content" id="post-body-content">
    <h2 class="tabs" id="post-body-content-tabs">
        <a href="?page=sphinxsearch.php" class="nav-tab nav-tab-active">Settings</a>
        <a href="?page=sphinxsearch.php&menu=stats" class="nav-tab">Search terms</a>
    </h2>
        
        <div class="meta-box-sortabless">
            <div class="postbox">
                <h3 class="hndle">Sphinx service management</h3>
                <div class="inside">
                    <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
                    <fieldset class="options">
                         <?php if ($this->view->devOptions['sphinx_running'] == 'true'): ?>
                            Sphinx Search Server is running.<br/>
                         <?php else: ?>
                            <span style="color:red">Sphinx Search Server is NOT running.</span><br/>
                         <?php endif; ?>
                    </fieldset>
                    <p class="submit">
                        <?php if ($this->view->devOptions['sphinx_running'] == 'true'): ?>                            
                            <input type="submit" style="width:300px;" name="stop_sphinx" class="button-primary"
                                   value="Stop Sphinx daemon" />
                        <?php else: ?>                            
                            <input type="submit" style="width:300px;" name="start_sphinx" class="button-primary"
                                   value="Start Sphinx daemon" />
                        <?php endif; ?>
                    </p>
                    </form>
                </div>
            </div>

            <div class="postbox">
                <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
                <h3 class="hndle">Index management</h3>
                <div class="inside">
                    <fieldset class="options">
                    </fieldset>
                    <p class="submit">
                        <input type="submit" style="width:300px;" name="reindex_sphinx" class="button-primary"
                               value="Re-index WordPress index now" />
                    </p>
                </div>
                </form>
            </div>

            <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
            <div class="postbox">
                <h3 class="hndle">Search in</h3>
                <div class="inside">
                    <fieldset class="options">

                    <table class="form-table" border="0">
                    <tbody>
                    <tr valign="top" >
                        <th><label for="search_comments">Comments</label></th>
                        <td>
                        <input type="checkbox" id="search_comments" name="search_comments" value="true"
                        <?php if ($this->view->devOptions['search_comments'] == "true")
                        { _e('checked="checked"', "SphinxSearch"); }?>/>
                        </td>
                    </tr>
                    <tr valign="top" >
                        <th><label for="search_posts">Posts</label></th>
                        <td>
                            <input type="checkbox" id="search_posts" name="search_posts" value="true"
                            <?php if ($this->view->devOptions['search_posts'] == "true")
                                { _e('checked="checked"', "SphinxSearch"); }?>/>
                        </td>
                    </tr>
                    <tr valign="top" >
                        <th ><label for="search_pages">Pages</label></th>
                        <td><input type="checkbox" id="search_pages" name="search_pages" value="true"
                            <?php if ($this->view->devOptions['search_pages'] == "true")
                            { _e('checked="checked"', "SphinxSearch"); }?>/>
                            </td>
                    </tr>
                    </tbody>
                    </table>
                    </fieldset>
                    <p class="submit">
                        <input type="submit" name="update_SphinxSearchSettings" class="button-primary"
                        value="<?php _e('Update Settings', 'SphinxSearch') ?>" />
                    </p>
                </div>
            </div>

           <div class="postbox">
                <h3 class="hndle">Keyword wrapper settings</h3>
                <div class="inside">
                    <fieldset class="options">
                    <table class="form-table">
                    <tbody>
                    <tr valign="top" >
                        <th scope="row">Before keyword in text</th>
                        <td ><input type="text" id="excerpt_before_match" name="excerpt_before_match"
                            value="<?php echo $this->view->devOptions['excerpt_before_match'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">After keyword in text</th>
                        <td ><input type="text" id="excerpt_after_match" name="excerpt_after_match"
                        value="<?php echo $this->view->devOptions['excerpt_after_match'];?>" /> </td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Before keyword in title</th>
                        <td ><input type="text" id="excerpt_before_match_title" name="excerpt_before_match_title"
                        value="<?php echo $this->view->devOptions['excerpt_before_match_title'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">After keyword in title</th>
                        <td ><input type="text" id="excerpt_after_match_title" name="excerpt_after_match_title"
                            value="<?php echo $this->view->devOptions['excerpt_after_match_title'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Snippet separator</th>
                        <td ><input type="text" id="excerpt_chunk_separator" name="excerpt_chunk_separator"
                            value="<?php echo $this->view->devOptions['excerpt_chunk_separator'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Snippet max length</th>
                        <td ><input type="text" id="excerpt_limit" name="excerpt_limit" size="4"
                            value="<?php echo $this->view->devOptions['excerpt_limit'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Maximum number of words around keyword</th>
                        <td ><input type="text" id="excerpt_around" name="excerpt_around" size="4"
                            value="<?php echo $this->view->devOptions['excerpt_around'];?>" /> </td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Prefix before Comment title</th>
                        <td ><input type="text" id="before_comment" name="before_comment"
                            value="<?php echo $this->view->devOptions['before_comment'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Prefix before Page title</th>
                        <td ><input type="text" id="before_page" name="before_page"
                            value="<?php echo $this->view->devOptions['before_page'];?>" /> </td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Prefix before Post title</th>
                        <td ><input type="text" id="before_post" name="before_post"
                            value="<?php echo $this->view->devOptions['before_post'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">List of phrases to cut from search results (one phrase per line)</th>
                        <td><textarea id="strip_tags" name="strip_tags" rows="10"
                                      cols="25"><?php echo $this->view->devOptions['strip_tags'];?></textarea></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">List of not censor phrases to cut from search statistics (one phrase per line)</th>
                        <td ><textarea id="censor_words" name="censor_words" rows="10"
                                       cols="25"><?php echo $this->view->devOptions['censor_words'];?></textarea></td>
                    </tr>
                    </tbody>
                    </table>
                    </fieldset>
                    <p class="submit">
                        <input type="submit" name="update_SphinxSearchSettings" class="button-primary"
                            value="<?php _e('Update Settings', 'SphinxSearch') ?>" />
                    </p>
                </div>
           </div>

           <div class="postbox">
                <h3 class="hndle">Sphinx сonfiguration</h3>
                <div class="inside">
                    <fieldset class="options">
                    <table class="form-table" border="0" >
                    <tbody>
                    <tr valign="top" >
                        <th scope="row">Sphinx index name</th>
                        <td ><input type="text" id="sphinx_index" name="sphinx_index"
                            value="<?php echo $this->view->devOptions['sphinx_index'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Sphinx port (default 3312)</th>
                        <td ><input type="text" id="sphinx_port" name="sphinx_port"  size="4"
                            value="<?php echo $this->view->devOptions['sphinx_port'];?>" /></td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Sphinx configuration file path</th>
                        <td ><input type="text" id="sphinx_conf" name="sphinx_conf" size="30"
                        value="<?php echo $this->view->devOptions['sphinx_conf'];?>" /> (<?php echo !file_exists($this->view->devOptions['sphinx_conf'])?'<font color="red">Doesn\'t exist</font>':'<font color="green">Exists</font>';?>)</td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Sphinx searchd file path</th>
                        <td ><input type="text" id="sphinx_searchd" name="sphinx_searchd" size="30"
                            value="<?php echo $this->view->devOptions['sphinx_searchd'];?>" /> (<?php echo !file_exists($this->view->devOptions['sphinx_searchd'])?'<font color="red">Doesn\'t exist</font>':'<font color="green">Exists</font>';?>)</td>
                    </tr>
                    <tr valign="top" >
                        <th scope="row">Sphinx indexer file path</th>
                        <td ><input type="text" id="sphinx_indexer" name="sphinx_indexer" size="30"
                            value="<?php echo $this->view->devOptions['sphinx_indexer'];?>" /> (<?php echo !file_exists($this->view->devOptions['sphinx_indexer'])?'<font color="red">Doesn\'t exist</font>':'<font color="green">Exists</font>';?>)</td>
                    </tr>
                    </tbody>
                    </table>
                    </fieldset>
                    <p class="submit">
                        <input type="submit" name="update_SphinxSearchSettings" class="button-primary"
                        value="<?php _e('Update settings', 'SphinxSearch') ?>" />
                    </p>
                </div>
           </div>
            </form>

            <div class="postbox">
                <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
                <input type="hidden" name="start_wizard" value="start" />
                <h3 class="hndle">Configuration Wizard</h3>
                    <div class="inside">
                    <p class="submit">
                            <input type="submit" style="width:300px;"
                                   class="button-primary"
                                   value="Run configuration Wizard" />
                    </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>