    <div class="metabox-holder has-right-sidebar" id="poststuff">
        <div class="inner-sidebar">
            <div style="position: relative;" class="meta-box-sortabless ui-sortable">
                <div class="postbox" id="sm_pnres">
                    <h3 class="hndle"><span>About this Plugin:</span></h3>
                    <div class="inside">
                        <a class="sm_button sm_pluginHome" href="http://www.ivinco.com/software/wordpress-sphinx-search-plugin/">Plugin Homepage</a>
                        <a class="sm_button sm_pluginSupport" href="http://wordpress.org/extend/plugins/wordpress-sphinx-plugin/">Support Forum</a>
                        <a class="sm_button sm_pluginCommercial" href="http://www.ivinco.com">Commercial Support</a>
                    </div>
                </div>
                <div class="postbox" id="sm_pnres">
                    <h3 class="hndle"><span>Usage:</span></h3>
                    <div class="inside">
                        To use Sphinx Search plugin you should go to
                        <a href="<?php echo get_bloginfo('url') ?>/wp-admin/widgets.php">Appearance->Widgets</a>
                        and enable the Sphinx widgets.<br/>
                        For installation instructions and more info please visit
                        WordPress Sphinx search 
                        <a href="http://www.ivinco.com/software/wordpress-sphinx-search-plugin/">plugin website</a>.
                    </div>
                </div>
            </div>
        </div>