    <div class="metabox-holder has-right-sidebar" id="poststuff">
        <div class="inner-sidebar">
            <div style="position: relative;" class="meta-box-sortabless ui-sortable">
                <div class="postbox" id="sm_pnres">
                <h3 class="hndle"><span>About this Plugin:</span></h3>
                <div class="inside">
                <a class="sm_button sm_pluginHome" href="http://www.ivinco.com/software/">Plugin Homepage</a>
                <a class="sm_button sm_pluginSupport" href="http://wordpress.org/extend/plugins/wordpress-sphinx-plugin/">Support Forum</a>
                </div>
                </div>
            </div>
        </div>