<?php echo $this->render('admin/messagebox.phtml'); ?>
<div class="postbox">
    <h3 class="hndle">Sphinx configuration file</h3>
    <div class="inside">
        <table class="form-table">
            <tr>
                <th>sphinx.conf is saved at</th>
                <td><?php echo $this->view->sphinx_conf?></td>
            </tr>
        </table>
        <form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post"  id="wizard_form">
            <input type="hidden" name="config_process" value="true" />
            <input type="hidden" name="action" value="config" />
            <p class="submit">
                <input class="button-secondary cancel" type="button"
                       onClick="return wizard_skip('config');" value="Skip step" />
                <input type="button"  onClick="return wizard_next();"
                       value="Save &amp; Continue" class="button-primary" />
                 <input class="button-secondary cancel alignright" type="button"
                                       onClick="return wizard_cancel();" value="Cancel Wizard" />
            </p>
        </form>
    </div>

    <h3 class="hndle">Generated sphinx.conf</h3>
    <div class="inside">
        <a href="javascript:void(0);" onClick="$('#config_content').show();">Click here to see Sphinx configuration</a>
        <div style="display:none" id="config_content">
        <textarea rows="100" cols="80"><?php echo htmlentities($this->view->config_content)?></textarea>
        </div>
    </div>
</div>
