<?php echo $this->render('admin/messagebox.phtml'); ?>
<div class="postbox">
    <h3 class="hndle">Sphinx data indexing</h3>
    <div class="inside">

        <form action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" id="wizard_form">
                <input type="hidden" name="process_indexing" value="1" />
                <input type="hidden" name="action" value="indexing" />
                <p class="submit">
                    <input class="button-primary" type="button"
                       onClick="return wizard_skip('indexsation');" value="Skip step" />
                    <input type="button" class="button-primary"
                       value="Run indexing &amp; Continue" onClick="return wizard_next();" />
                     <input class="button-primary" type="button"
                                       style="float:right"
                                       onClick="return wizard_cancel();" value="Cancel Wizard" />
                </p>
        </form>
    </div>
</div>