<?php echo $this->render('admin/messagebox.phtml'); ?>
<div class="postbox">
    <h3 class="hndle">Sphinx configuration finished</h3>
    <div class="inside">
        <table class="form-table">
            <tr>
                <th>sphinx.conf is saved at</th>
                <td><?php echo $this->view->sphinx_conf?></td>
            </tr>
        </table>
        <form  action="options-general.php?page=sphinxsearch.php" method="post"  id="wizard_form">
            <input type="hidden" name="done_wizard" value="true" />
            <p class="submit">
                <input type="submit" value="Finish" class="button-primary" />
            </p>
        </form>
    </div>

    <h3 class="hndle">Generated sphinx.conf</h3>
    <div class="inside">
        <a href="javascript:void(0);" onClick="$('#config_content').show();">Click here to see Sphinx configuration</a>
        <div style="display:none" id="config_content">
        <textarea rows="100" cols="80"><?php echo htmlentities($this->view->config_content)?></textarea>
        </div>
    </div>
</div>
