<?php echo $this->render('admin/header.phtml');?>
<?php echo $this->render('admin/sidebar.phtml');?>

<div class="has-sidebar sm-padded" >
    <div class="has-sidebar-content" id="post-body-content">
        <div class="meta-box-sortabless">
            <div id="wizard_page">
                <div class="postbox">
                    <h3 class="hndle">Sphinx Search Wizard</h3>
                    <div class="inside">
                    <form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" id="wizard_form">
                        <input type="hidden" name="start_process" value="1" />
                        <input type="hidden" name="action" value="start" />
                        <p>Some warning message about running Wizard!</p>
                            <p class="submit">
                                <input class="button-primary" type="button"
                                       onClick="return wizard_next();" value="Do you really want to run Wizard?" />
                            </p>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render('admin/footer.phtml');?>