<div class=wrap>
    <h2>Sphinx Search :: Configuration Wizard</h2>

    <div class="metabox-holder has-right-sidebar" id="poststuff">
    <div class="inner-sidebar"></div>
    <div style="position: relative;" class="meta-box-sortabless ui-sortable" id="side-sortables">

<div id="wizard_page">
    <?php echo $this->render('admin/messagebox.phtml'); ?>
    <div class="postbox">
        <h3 class="hndle">Set sphinx connection parameters</h3>
        <div class="inside">

        <form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" id="wizard_form">
            <input type="hidden" name="connection_process" value="1" />
            <input type="hidden" name="action" value="connection" />
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="sphinx_host">Host name</label></th>
                    <td>
                        <input type="text" name="sphinx_host" id="sphinx_host"
                         value="<?php echo $this->view->sphinx_host?>" />
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="sphinx_port">Port</label></th>
                    <td>
                        <input type="text" name="sphinx_port" id="sphinx_port"
                               value="<?php echo $this->view->sphinx_port?>" />
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="sphinx_index">Index prefix</label></th>
                    <td>
                        <input type="text" name="sphinx_index" id="sphinx_index"
                               value="<?php echo $this->view->sphinx_index?>" />
                    </td>
                </tr>
            </table>
                <p class="submit">
                    <input class="button-primary" type="button"
                           onClick="return wizard_next();" value="Save &amp; Continue" />
                </p>
        </form>
        </div>
    </div>
</div>
</div>
</div>
</div>