<div style="width: 400px;">
        <ul class="subsubsub" >
            <?php if($this->view->tab == 'new'):?>
                <li class='all'><a href='?page=sphinxsearch.php&menu=terms_editor' class="current">New search terms</a> |</li>
            <?php else:?>
                <li class='all'><a href='?page=sphinxsearch.php&menu=terms_editor'>New search terms</a> |</li>
            <?php endif; ?>
            <?php if($this->view->tab == 'ban'):?>
                <li class='moderated'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=ban' class="current">Banned search terms</a> |</li>
            <?php else:?>
                <li class='moderated'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=ban'>Banned search terms</a> |</li>
            <?php endif; ?>
            <?php if($this->view->tab == 'approved'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=approved' class="current">Approved search terms</a>  </li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=approved'>Approved search terms</a>  </li>
            <?php endif; ?>
                <br/>
            <?php if($this->view->tab == 'import'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=import' class="current">Import search terms</a>  |</li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=import'>Import search terms</a>  |</li>
            <?php endif; ?>                
            <?php if($this->view->tab == 'export'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=export' class="current">Export search terms</a>  |</li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=export'>Export search terms</a>  |</li>
            <?php endif; ?>
            <?php if($this->view->tab == 'blacklist'):?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=blacklist' class="current">Keyword Blacklist</a> </li>
            <?php else:?>
                <li class='approved'><a href='?page=sphinxsearch.php&menu=terms_editor&tab=blacklist'>Keyword Blacklist</a> </li>
            <?php endif; ?>
        </ul>
</div>

    <?php  
    switch($this->view->tab){
        case 'blacklist':
            echo $this->render('admin/terms_editor/blacklist.phtml');
            break;
        case 'import':
            echo $this->render('admin/terms_editor/import.phtml');
            break;
        case 'export':
            echo $this->render('admin/terms_editor/export.phtml');
            break;
        case 'new':
        case 'ban':
        case 'approved':
        default:
            echo $this->render('admin/terms_editor/index.phtml');
        break;
    }
    ?>
    </div>
</div>

