<form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post">
    <input type="hidden" name="wizard_process" value="1" />
    <input type="hidden" name="wizard_step" value="2" />
    <?php if($sphinx_detect_searchd):?>
        Sphinx Detected at the system:<br/>
        searchd path: <input type="text" name="detected_searchd" value="<?php echo $sphinx_detect_searchd?>" /> <br/>
        indexer path: <input type="text" name="detected_indexer" value="<?php echo $sphinx_detect_indexer?>" /> <br/>
        Do you want to use detected one or make a fresh install at <?php echo $sphinx_install_path?>?<br/>
        <input type="submit" name="use_detected_sphinx" value="Use detected Sphinx" /> or
    <?php else:?>
        Sphinx is not installed on the system.<br/>
        Do you want to make a fresh install at <?php echo $sphinx_install_path?>?<br/>
    <?php endif; ?>
    <input type="submit" name="install_sphinx" value="Make fresh install" />
</form>