<form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post">
    
    <h2>Indexing</h2>
    <?php if ($indexsation_done):?>
        <div class="updated"><p><strong>Indexing done</strong></p></div>
        <input type="hidden" name="wizard_step" value="5" />
        <input type="submit" value="Continue to next step" />
    <?php else:?>
        <input type="hidden" name="wizard_process" value="1" />
        <input type="hidden" name="wizard_step" value="4" />
        <input type="submit" value="Run data indexing" />
    <?php endif; ?>
        
</form>