<h2>Setup Sphinx connection parameters</h2>

<form  action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post">
    <input type="hidden" name="wizard_process" value="1" />
    <input type="hidden" name="wizard_step" value="1" />
        Host: <input type="text" name="sphinx_host" value="<?php echo !empty($_POST['sphinx_host']) ? $_POST['sphinx_host'] : $options['sphinx_host']?>" /> <br/>
        Port: <input type="text" name="sphinx_port" value="<?php echo !empty($_POST['sphinx_port']) ? $_POST['sphinx_port'] : $options['sphinx_port']?>" /> <br/>
        Index prefix: <input type="text" name="sphinx_index" value="<?php echo !empty($_POST['sphinx_index']) ? $_POST['sphinx_index'] : $options['sphinx_index']?>" /> <br/>
        <input type="submit" value="Save and continue to step 2" />
</form>